// ==========================================================================
// Verb Conjugation Seed Data — German (Top 50) + French (Top 50)
// ==========================================================================
// Run with: npx tsx supabase/seed/conjugation_seed.ts
//
// Each verb includes all forms for:
//   German: Präsens, Präteritum, Perfekt, Futur I, Konjunktiv II
//   French: Présent, Imparfait, Passé composé, Futur simple, Conditionnel
// across all 6 standard pronouns.

import type { VerbSeedData } from "@/types/conjugation";

// Helper to generate all 6 pronoun forms for a German verb
function deVerb(
  infinitive: string,
  english: string,
  verbClass: string,
  rank: number,
  tags: string[],
  present: [string, string, string, string, string, string],
  preterite: [string, string, string, string, string, string],
  perfect: [string, string, string, string, string, string],
  future: [string, string, string, string, string, string],
  subjunctiveII: [string, string, string, string, string, string],
  explanations?: Partial<Record<string, string>>,
): VerbSeedData {
  const pronouns = ["ich", "du", "er/sie/es", "wir", "ihr", "sie/Sie"];
  const keys = ["1sg", "2sg", "3sg", "1pl", "2pl", "3pl"] as const;

  const forms: VerbSeedData["forms"] = [];

  const addForms = (
    tense: string,
    mood: string,
    conjugations: string[],
    explanationKey?: string,
  ) => {
    conjugations.forEach((form, i) => {
      const ruleKey = explanationKey
        ? `${explanationKey}_${keys[i]}`
        : undefined;
      forms.push({
        tense,
        mood,
        pronoun: pronouns[i],
        pronoun_key: keys[i],
        conjugated_form: form,
        rule_explanation: ruleKey
          ? (explanations?.[ruleKey] ?? explanations?.[explanationKey!])
          : undefined,
      });
    });
  };

  addForms("present", "indicative", [...present], "present");
  addForms("preterite", "indicative", [...preterite], "preterite");
  addForms("perfect", "indicative", [...perfect], "perfect");
  addForms("future", "indicative", [...future], "future");
  addForms(
    "subjunctive_imperfect",
    "subjunctive",
    [...subjunctiveII],
    "subjunctive_ii",
  );

  return {
    language: "de",
    infinitive,
    english_meaning: english,
    verb_class: verbClass,
    frequency_rank: rank,
    tags,
    forms,
  };
}

export const GERMAN_VERBS: VerbSeedData[] = [
  deVerb(
    "sein",
    "to be",
    "irregular",
    1,
    ["common", "auxiliary"],
    ["bin", "bist", "ist", "sind", "seid", "sind"],
    ["war", "warst", "war", "waren", "wart", "waren"],
    [
      "bin gewesen",
      "bist gewesen",
      "ist gewesen",
      "sind gewesen",
      "seid gewesen",
      "sind gewesen",
    ],
    [
      "werde sein",
      "wirst sein",
      "wird sein",
      "werden sein",
      "werdet sein",
      "werden sein",
    ],
    ["wäre", "wärst", "wäre", "wären", "wärt", "wären"],
    {
      present: "Highly irregular verb — all forms must be memorised",
      preterite: "Irregular Präteritum stem: war-",
      subjunctive_ii:
        "Konjunktiv II formed from Präteritum stem with umlaut: wär-",
    },
  ),
  deVerb(
    "haben",
    "to have",
    "irregular",
    2,
    ["common", "auxiliary"],
    ["habe", "hast", "hat", "haben", "habt", "haben"],
    ["hatte", "hattest", "hatte", "hatten", "hattet", "hatten"],
    [
      "habe gehabt",
      "hast gehabt",
      "hat gehabt",
      "haben gehabt",
      "habt gehabt",
      "haben gehabt",
    ],
    [
      "werde haben",
      "wirst haben",
      "wird haben",
      "werden haben",
      "werdet haben",
      "werden haben",
    ],
    ["hätte", "hättest", "hätte", "hätten", "hättet", "hätten"],
    {
      present: "Irregular: du hast, er hat (not habst/habt)",
      subjunctive_ii: "Konjunktiv II: hätt- (umlaut on Präteritum stem)",
    },
  ),
  deVerb(
    "werden",
    "to become",
    "irregular",
    3,
    ["common", "auxiliary"],
    ["werde", "wirst", "wird", "werden", "werdet", "werden"],
    ["wurde", "wurdest", "wurde", "wurden", "wurdet", "wurden"],
    [
      "bin geworden",
      "bist geworden",
      "ist geworden",
      "sind geworden",
      "seid geworden",
      "sind geworden",
    ],
    [
      "werde werden",
      "wirst werden",
      "wird werden",
      "werden werden",
      "werdet werden",
      "werden werden",
    ],
    ["würde", "würdest", "würde", "würden", "würdet", "würden"],
    {
      present: "Irregular: stem vowel e→i in 2sg/3sg: wirst, wird",
      perfect: "Uses sein as auxiliary: bin geworden",
    },
  ),
  deVerb(
    "können",
    "to be able to, can",
    "modal",
    4,
    ["common", "modal"],
    ["kann", "kannst", "kann", "können", "könnt", "können"],
    ["konnte", "konntest", "konnte", "konnten", "konntet", "konnten"],
    [
      "habe gekonnt",
      "hast gekonnt",
      "hat gekonnt",
      "haben gekonnt",
      "habt gekonnt",
      "haben gekonnt",
    ],
    [
      "werde können",
      "wirst können",
      "wird können",
      "werden können",
      "werdet können",
      "werden können",
    ],
    ["könnte", "könntest", "könnte", "könnten", "könntet", "könnten"],
    {
      present:
        "Modal verb: vowel change ö→a in singular present. 1sg/3sg have no ending.",
      subjunctive_ii: "Konjunktiv II: könnt- (umlaut restored)",
    },
  ),
  deVerb(
    "müssen",
    "to have to, must",
    "modal",
    5,
    ["common", "modal"],
    ["muss", "musst", "muss", "müssen", "müsst", "müssen"],
    ["musste", "musstest", "musste", "mussten", "musstet", "mussten"],
    [
      "habe gemusst",
      "hast gemusst",
      "hat gemusst",
      "haben gemusst",
      "habt gemusst",
      "haben gemusst",
    ],
    [
      "werde müssen",
      "wirst müssen",
      "wird müssen",
      "werden müssen",
      "werdet müssen",
      "werden müssen",
    ],
    ["müsste", "müsstest", "müsste", "müssten", "müsstet", "müssten"],
    {
      present:
        "Modal verb: vowel change ü→u in singular. 1sg/3sg have no ending.",
    },
  ),
  deVerb(
    "sollen",
    "should, to be supposed to",
    "modal",
    6,
    ["common", "modal"],
    ["soll", "sollst", "soll", "sollen", "sollt", "sollen"],
    ["sollte", "solltest", "sollte", "sollten", "solltet", "sollten"],
    [
      "habe gesollt",
      "hast gesollt",
      "hat gesollt",
      "haben gesollt",
      "habt gesollt",
      "haben gesollt",
    ],
    [
      "werde sollen",
      "wirst sollen",
      "wird sollen",
      "werden sollen",
      "werdet sollen",
      "werden sollen",
    ],
    ["sollte", "solltest", "sollte", "sollten", "solltet", "sollten"],
    { present: "Modal verb: no vowel change. 1sg/3sg have no ending." },
  ),
  deVerb(
    "wollen",
    "to want",
    "modal",
    7,
    ["common", "modal"],
    ["will", "willst", "will", "wollen", "wollt", "wollen"],
    ["wollte", "wolltest", "wollte", "wollten", "wolltet", "wollten"],
    [
      "habe gewollt",
      "hast gewollt",
      "hat gewollt",
      "haben gewollt",
      "habt gewollt",
      "haben gewollt",
    ],
    [
      "werde wollen",
      "wirst wollen",
      "wird wollen",
      "werden wollen",
      "werdet wollen",
      "werden wollen",
    ],
    ["wollte", "wolltest", "wollte", "wollten", "wolltet", "wollten"],
    {
      present:
        "Modal verb: stem change in singular: woll→will. 1sg/3sg have no ending.",
    },
  ),
  deVerb(
    "dürfen",
    "to be allowed to, may",
    "modal",
    8,
    ["common", "modal"],
    ["darf", "darfst", "darf", "dürfen", "dürft", "dürfen"],
    ["durfte", "durftest", "durfte", "durften", "durftet", "durften"],
    [
      "habe gedurft",
      "hast gedurft",
      "hat gedurft",
      "haben gedurft",
      "habt gedurft",
      "haben gedurft",
    ],
    [
      "werde dürfen",
      "wirst dürfen",
      "wird dürfen",
      "werden dürfen",
      "werdet dürfen",
      "werden dürfen",
    ],
    ["dürfte", "dürftest", "dürfte", "dürften", "dürftet", "dürften"],
    {
      present:
        "Modal verb: vowel change ü→a in singular. 1sg/3sg have no ending.",
    },
  ),
  deVerb(
    "mögen",
    "to like",
    "modal",
    9,
    ["common", "modal"],
    ["mag", "magst", "mag", "mögen", "mögt", "mögen"],
    ["mochte", "mochtest", "mochte", "mochten", "mochtet", "mochten"],
    [
      "habe gemocht",
      "hast gemocht",
      "hat gemocht",
      "haben gemocht",
      "habt gemocht",
      "haben gemocht",
    ],
    [
      "werde mögen",
      "wirst mögen",
      "wird mögen",
      "werden mögen",
      "werdet mögen",
      "werden mögen",
    ],
    ["möchte", "möchtest", "möchte", "möchten", "möchtet", "möchten"],
    {
      present: "Modal verb: vowel change ö→a in singular.",
      subjunctive_ii: "Konjunktiv II möchte is very common as 'would like'",
    },
  ),
  deVerb(
    "gehen",
    "to go",
    "strong",
    10,
    ["common"],
    ["gehe", "gehst", "geht", "gehen", "geht", "gehen"],
    ["ging", "gingst", "ging", "gingen", "gingt", "gingen"],
    [
      "bin gegangen",
      "bist gegangen",
      "ist gegangen",
      "sind gegangen",
      "seid gegangen",
      "sind gegangen",
    ],
    [
      "werde gehen",
      "wirst gehen",
      "wird gehen",
      "werden gehen",
      "werdet gehen",
      "werden gehen",
    ],
    ["ginge", "gingest", "ginge", "gingen", "ginget", "gingen"],
    {
      preterite: "Strong verb: stem vowel change eh→i: ging",
      perfect: "Uses sein as auxiliary (verb of motion): bin gegangen",
    },
  ),
  deVerb(
    "kommen",
    "to come",
    "strong",
    11,
    ["common"],
    ["komme", "kommst", "kommt", "kommen", "kommt", "kommen"],
    ["kam", "kamst", "kam", "kamen", "kamt", "kamen"],
    [
      "bin gekommen",
      "bist gekommen",
      "ist gekommen",
      "sind gekommen",
      "seid gekommen",
      "sind gekommen",
    ],
    [
      "werde kommen",
      "wirst kommen",
      "wird kommen",
      "werden kommen",
      "werdet kommen",
      "werden kommen",
    ],
    ["käme", "kämest", "käme", "kämen", "kämet", "kämen"],
    {
      preterite: "Strong verb: stem vowel change o→a: kam",
      perfect: "Uses sein (verb of motion): bin gekommen",
    },
  ),
  deVerb(
    "sagen",
    "to say",
    "weak",
    12,
    ["common"],
    ["sage", "sagst", "sagt", "sagen", "sagt", "sagen"],
    ["sagte", "sagtest", "sagte", "sagten", "sagtet", "sagten"],
    [
      "habe gesagt",
      "hast gesagt",
      "hat gesagt",
      "haben gesagt",
      "habt gesagt",
      "haben gesagt",
    ],
    [
      "werde sagen",
      "wirst sagen",
      "wird sagen",
      "werden sagen",
      "werdet sagen",
      "werden sagen",
    ],
    ["sagte", "sagtest", "sagte", "sagten", "sagtet", "sagten"],
  ),
  deVerb(
    "machen",
    "to make, to do",
    "weak",
    13,
    ["common"],
    ["mache", "machst", "macht", "machen", "macht", "machen"],
    ["machte", "machtest", "machte", "machten", "machtet", "machten"],
    [
      "habe gemacht",
      "hast gemacht",
      "hat gemacht",
      "haben gemacht",
      "habt gemacht",
      "haben gemacht",
    ],
    [
      "werde machen",
      "wirst machen",
      "wird machen",
      "werden machen",
      "werdet machen",
      "werden machen",
    ],
    ["machte", "machtest", "machte", "machten", "machtet", "machten"],
  ),
  deVerb(
    "wissen",
    "to know (a fact)",
    "irregular",
    14,
    ["common"],
    ["weiß", "weißt", "weiß", "wissen", "wisst", "wissen"],
    ["wusste", "wusstest", "wusste", "wussten", "wusstet", "wussten"],
    [
      "habe gewusst",
      "hast gewusst",
      "hat gewusst",
      "haben gewusst",
      "habt gewusst",
      "haben gewusst",
    ],
    [
      "werde wissen",
      "wirst wissen",
      "wird wissen",
      "werden wissen",
      "werdet wissen",
      "werden wissen",
    ],
    ["wüsste", "wüsstest", "wüsste", "wüssten", "wüsstet", "wüssten"],
    {
      present:
        "Mixed verb: present tense like a modal verb (weiß, no ending for 1sg/3sg)",
      preterite: "Irregular Präteritum: wusst-",
    },
  ),
  deVerb(
    "sehen",
    "to see",
    "strong",
    15,
    ["common"],
    ["sehe", "siehst", "sieht", "sehen", "seht", "sehen"],
    ["sah", "sahst", "sah", "sahen", "saht", "sahen"],
    [
      "habe gesehen",
      "hast gesehen",
      "hat gesehen",
      "haben gesehen",
      "habt gesehen",
      "haben gesehen",
    ],
    [
      "werde sehen",
      "wirst sehen",
      "wird sehen",
      "werden sehen",
      "werdet sehen",
      "werden sehen",
    ],
    ["sähe", "sähest", "sähe", "sähen", "sähet", "sähen"],
    { present: "Strong verb: vowel change e→ie in 2sg/3sg: siehst, sieht" },
  ),
  deVerb(
    "lassen",
    "to let, to leave",
    "strong",
    16,
    ["common"],
    ["lasse", "lässt", "lässt", "lassen", "lasst", "lassen"],
    ["ließ", "ließest", "ließ", "ließen", "ließt", "ließen"],
    [
      "habe gelassen",
      "hast gelassen",
      "hat gelassen",
      "haben gelassen",
      "habt gelassen",
      "haben gelassen",
    ],
    [
      "werde lassen",
      "wirst lassen",
      "wird lassen",
      "werden lassen",
      "werdet lassen",
      "werden lassen",
    ],
    ["ließe", "ließest", "ließe", "ließen", "ließet", "ließen"],
    { present: "Strong verb: vowel change a→ä in 2sg/3sg: lässt" },
  ),
  deVerb(
    "stehen",
    "to stand",
    "strong",
    17,
    ["common"],
    ["stehe", "stehst", "steht", "stehen", "steht", "stehen"],
    ["stand", "standest", "stand", "standen", "standet", "standen"],
    [
      "habe gestanden",
      "hast gestanden",
      "hat gestanden",
      "haben gestanden",
      "habt gestanden",
      "haben gestanden",
    ],
    [
      "werde stehen",
      "wirst stehen",
      "wird stehen",
      "werden stehen",
      "werdet stehen",
      "werden stehen",
    ],
    ["stände", "ständest", "stände", "ständen", "ständet", "ständen"],
    { preterite: "Strong verb: Präteritum stem vowel change eh→a: stand" },
  ),
  deVerb(
    "finden",
    "to find",
    "strong",
    18,
    ["common"],
    ["finde", "findest", "findet", "finden", "findet", "finden"],
    ["fand", "fandest", "fand", "fanden", "fandet", "fanden"],
    [
      "habe gefunden",
      "hast gefunden",
      "hat gefunden",
      "haben gefunden",
      "habt gefunden",
      "haben gefunden",
    ],
    [
      "werde finden",
      "wirst finden",
      "wird finden",
      "werden finden",
      "werdet finden",
      "werden finden",
    ],
    ["fände", "fändest", "fände", "fänden", "fändet", "fänden"],
    {
      preterite: "Strong verb: vowel change i→a: fand",
      perfect: "Past participle: gefunden (i→u)",
    },
  ),
  deVerb(
    "bleiben",
    "to stay, to remain",
    "strong",
    19,
    ["common"],
    ["bleibe", "bleibst", "bleibt", "bleiben", "bleibt", "bleiben"],
    ["blieb", "bliebst", "blieb", "blieben", "bliebt", "blieben"],
    [
      "bin geblieben",
      "bist geblieben",
      "ist geblieben",
      "sind geblieben",
      "seid geblieben",
      "sind geblieben",
    ],
    [
      "werde bleiben",
      "wirst bleiben",
      "wird bleiben",
      "werden bleiben",
      "werdet bleiben",
      "werden bleiben",
    ],
    ["bliebe", "bliebest", "bliebe", "blieben", "bliebet", "blieben"],
    {
      preterite: "Strong verb: vowel change ei→ie: blieb",
      perfect: "Uses sein (change of state): bin geblieben",
    },
  ),
  deVerb(
    "heißen",
    "to be called",
    "strong",
    20,
    ["common"],
    ["heiße", "heißt", "heißt", "heißen", "heißt", "heißen"],
    ["hieß", "hießest", "hieß", "hießen", "hießt", "hießen"],
    [
      "habe geheißen",
      "hast geheißen",
      "hat geheißen",
      "haben geheißen",
      "habt geheißen",
      "haben geheißen",
    ],
    [
      "werde heißen",
      "wirst heißen",
      "wird heißen",
      "werden heißen",
      "werdet heißen",
      "werden heißen",
    ],
    ["hieße", "hießest", "hieße", "hießen", "hießet", "hießen"],
    { preterite: "Strong verb: vowel change ei→ie: hieß" },
  ),
  deVerb(
    "geben",
    "to give",
    "strong",
    21,
    ["common"],
    ["gebe", "gibst", "gibt", "geben", "gebt", "geben"],
    ["gab", "gabst", "gab", "gaben", "gabt", "gaben"],
    [
      "habe gegeben",
      "hast gegeben",
      "hat gegeben",
      "haben gegeben",
      "habt gegeben",
      "haben gegeben",
    ],
    [
      "werde geben",
      "wirst geben",
      "wird geben",
      "werden geben",
      "werdet geben",
      "werden geben",
    ],
    ["gäbe", "gäbest", "gäbe", "gäben", "gäbet", "gäben"],
    { present: "Strong verb: vowel change e→i in 2sg/3sg: gibst, gibt" },
  ),
  deVerb(
    "nehmen",
    "to take",
    "strong",
    22,
    ["common"],
    ["nehme", "nimmst", "nimmt", "nehmen", "nehmt", "nehmen"],
    ["nahm", "nahmst", "nahm", "nahmen", "nahmt", "nahmen"],
    [
      "habe genommen",
      "hast genommen",
      "hat genommen",
      "haben genommen",
      "habt genommen",
      "haben genommen",
    ],
    [
      "werde nehmen",
      "wirst nehmen",
      "wird nehmen",
      "werden nehmen",
      "werdet nehmen",
      "werden nehmen",
    ],
    ["nähme", "nähmest", "nähme", "nähmen", "nähmet", "nähmen"],
    {
      present:
        "Strong verb: vowel change e→i + consonant doubling in 2sg/3sg: nimmst, nimmt",
    },
  ),
  deVerb(
    "denken",
    "to think",
    "mixed",
    23,
    ["common"],
    ["denke", "denkst", "denkt", "denken", "denkt", "denken"],
    ["dachte", "dachtest", "dachte", "dachten", "dachtet", "dachten"],
    [
      "habe gedacht",
      "hast gedacht",
      "hat gedacht",
      "haben gedacht",
      "habt gedacht",
      "haben gedacht",
    ],
    [
      "werde denken",
      "wirst denken",
      "wird denken",
      "werden denken",
      "werdet denken",
      "werden denken",
    ],
    ["dächte", "dächtest", "dächte", "dächten", "dächtet", "dächten"],
    { preterite: "Mixed verb: weak -te ending but stem vowel change: dacht-" },
  ),
  deVerb(
    "fahren",
    "to drive, to go (by vehicle)",
    "strong",
    24,
    ["common"],
    ["fahre", "fährst", "fährt", "fahren", "fahrt", "fahren"],
    ["fuhr", "fuhrst", "fuhr", "fuhren", "fuhrt", "fuhren"],
    [
      "bin gefahren",
      "bist gefahren",
      "ist gefahren",
      "sind gefahren",
      "seid gefahren",
      "sind gefahren",
    ],
    [
      "werde fahren",
      "wirst fahren",
      "wird fahren",
      "werden fahren",
      "werdet fahren",
      "werden fahren",
    ],
    ["führe", "führest", "führe", "führen", "führet", "führen"],
    {
      present: "Strong verb: vowel change a→ä in 2sg/3sg: fährst, fährt",
      perfect: "Uses sein (verb of motion): bin gefahren",
    },
  ),
  deVerb(
    "schreiben",
    "to write",
    "strong",
    25,
    ["common"],
    ["schreibe", "schreibst", "schreibt", "schreiben", "schreibt", "schreiben"],
    ["schrieb", "schriebst", "schrieb", "schrieben", "schriebt", "schrieben"],
    [
      "habe geschrieben",
      "hast geschrieben",
      "hat geschrieben",
      "haben geschrieben",
      "habt geschrieben",
      "haben geschrieben",
    ],
    [
      "werde schreiben",
      "wirst schreiben",
      "wird schreiben",
      "werden schreiben",
      "werdet schreiben",
      "werden schreiben",
    ],
    [
      "schriebe",
      "schriebest",
      "schriebe",
      "schrieben",
      "schriebet",
      "schrieben",
    ],
    { preterite: "Strong verb: vowel change ei→ie: schrieb" },
  ),
  deVerb(
    "lesen",
    "to read",
    "strong",
    26,
    ["common"],
    ["lese", "liest", "liest", "lesen", "lest", "lesen"],
    ["las", "lasest", "las", "lasen", "last", "lasen"],
    [
      "habe gelesen",
      "hast gelesen",
      "hat gelesen",
      "haben gelesen",
      "habt gelesen",
      "haben gelesen",
    ],
    [
      "werde lesen",
      "wirst lesen",
      "wird lesen",
      "werden lesen",
      "werdet lesen",
      "werden lesen",
    ],
    ["läse", "läsest", "läse", "läsen", "läset", "läsen"],
    { present: "Strong verb: vowel change e→ie in 2sg/3sg: liest" },
  ),
  deVerb(
    "hören",
    "to hear",
    "weak",
    27,
    ["common"],
    ["höre", "hörst", "hört", "hören", "hört", "hören"],
    ["hörte", "hörtest", "hörte", "hörten", "hörtet", "hörten"],
    [
      "habe gehört",
      "hast gehört",
      "hat gehört",
      "haben gehört",
      "habt gehört",
      "haben gehört",
    ],
    [
      "werde hören",
      "wirst hören",
      "wird hören",
      "werden hören",
      "werdet hören",
      "werden hören",
    ],
    ["hörte", "hörtest", "hörte", "hörten", "hörtet", "hörten"],
  ),
  deVerb(
    "sprechen",
    "to speak",
    "strong",
    28,
    ["common"],
    ["spreche", "sprichst", "spricht", "sprechen", "sprecht", "sprechen"],
    ["sprach", "sprachst", "sprach", "sprachen", "spracht", "sprachen"],
    [
      "habe gesprochen",
      "hast gesprochen",
      "hat gesprochen",
      "haben gesprochen",
      "habt gesprochen",
      "haben gesprochen",
    ],
    [
      "werde sprechen",
      "wirst sprechen",
      "wird sprechen",
      "werden sprechen",
      "werdet sprechen",
      "werden sprechen",
    ],
    ["spräche", "sprächest", "spräche", "sprächen", "sprächet", "sprächen"],
    { present: "Strong verb: vowel change e→i in 2sg/3sg: sprichst, spricht" },
  ),
  deVerb(
    "bringen",
    "to bring",
    "mixed",
    29,
    ["common"],
    ["bringe", "bringst", "bringt", "bringen", "bringt", "bringen"],
    ["brachte", "brachtest", "brachte", "brachten", "brachtet", "brachten"],
    [
      "habe gebracht",
      "hast gebracht",
      "hat gebracht",
      "haben gebracht",
      "habt gebracht",
      "haben gebracht",
    ],
    [
      "werde bringen",
      "wirst bringen",
      "wird bringen",
      "werden bringen",
      "werdet bringen",
      "werden bringen",
    ],
    ["brächte", "brächtest", "brächte", "brächten", "brächtet", "brächten"],
    { preterite: "Mixed verb: weak ending -te but stem change: bracht-" },
  ),
  deVerb(
    "zeigen",
    "to show",
    "weak",
    30,
    ["common"],
    ["zeige", "zeigst", "zeigt", "zeigen", "zeigt", "zeigen"],
    ["zeigte", "zeigtest", "zeigte", "zeigten", "zeigtet", "zeigten"],
    [
      "habe gezeigt",
      "hast gezeigt",
      "hat gezeigt",
      "haben gezeigt",
      "habt gezeigt",
      "haben gezeigt",
    ],
    [
      "werde zeigen",
      "wirst zeigen",
      "wird zeigen",
      "werden zeigen",
      "werdet zeigen",
      "werden zeigen",
    ],
    ["zeigte", "zeigtest", "zeigte", "zeigten", "zeigtet", "zeigten"],
  ),
  deVerb(
    "kaufen",
    "to buy",
    "weak",
    31,
    ["common"],
    ["kaufe", "kaufst", "kauft", "kaufen", "kauft", "kaufen"],
    ["kaufte", "kauftest", "kaufte", "kauften", "kauftet", "kauften"],
    [
      "habe gekauft",
      "hast gekauft",
      "hat gekauft",
      "haben gekauft",
      "habt gekauft",
      "haben gekauft",
    ],
    [
      "werde kaufen",
      "wirst kaufen",
      "wird kaufen",
      "werden kaufen",
      "werdet kaufen",
      "werden kaufen",
    ],
    ["kaufte", "kauftest", "kaufte", "kauften", "kauftet", "kauften"],
  ),
  deVerb(
    "essen",
    "to eat",
    "strong",
    32,
    ["common"],
    ["esse", "isst", "isst", "essen", "esst", "essen"],
    ["aß", "aßest", "aß", "aßen", "aßt", "aßen"],
    [
      "habe gegessen",
      "hast gegessen",
      "hat gegessen",
      "haben gegessen",
      "habt gegessen",
      "haben gegessen",
    ],
    [
      "werde essen",
      "wirst essen",
      "wird essen",
      "werden essen",
      "werdet essen",
      "werden essen",
    ],
    ["äße", "äßest", "äße", "äßen", "äßet", "äßen"],
    { present: "Strong verb: vowel change e→i in 2sg/3sg: isst" },
  ),
  deVerb(
    "trinken",
    "to drink",
    "strong",
    33,
    ["common"],
    ["trinke", "trinkst", "trinkt", "trinken", "trinkt", "trinken"],
    ["trank", "trankst", "trank", "tranken", "trankt", "tranken"],
    [
      "habe getrunken",
      "hast getrunken",
      "hat getrunken",
      "haben getrunken",
      "habt getrunken",
      "haben getrunken",
    ],
    [
      "werde trinken",
      "wirst trinken",
      "wird trinken",
      "werden trinken",
      "werdet trinken",
      "werden trinken",
    ],
    ["tränke", "tränkest", "tränke", "tränken", "tränket", "tränken"],
    { preterite: "Strong verb: vowel change i→a: trank" },
  ),
  deVerb(
    "arbeiten",
    "to work",
    "weak",
    34,
    ["common"],
    ["arbeite", "arbeitest", "arbeitet", "arbeiten", "arbeitet", "arbeiten"],
    [
      "arbeitete",
      "arbeitetest",
      "arbeitete",
      "arbeiteten",
      "arbeitetet",
      "arbeiteten",
    ],
    [
      "habe gearbeitet",
      "hast gearbeitet",
      "hat gearbeitet",
      "haben gearbeitet",
      "habt gearbeitet",
      "haben gearbeitet",
    ],
    [
      "werde arbeiten",
      "wirst arbeiten",
      "wird arbeiten",
      "werden arbeiten",
      "werdet arbeiten",
      "werden arbeiten",
    ],
    [
      "arbeitete",
      "arbeitetest",
      "arbeitete",
      "arbeiteten",
      "arbeitetet",
      "arbeiteten",
    ],
    {
      present:
        "Weak verb with -e- insertion before consonant endings: du arbeitest, er arbeitet",
    },
  ),
  deVerb(
    "wohnen",
    "to live (reside)",
    "weak",
    35,
    ["common"],
    ["wohne", "wohnst", "wohnt", "wohnen", "wohnt", "wohnen"],
    ["wohnte", "wohntest", "wohnte", "wohnten", "wohntet", "wohnten"],
    [
      "habe gewohnt",
      "hast gewohnt",
      "hat gewohnt",
      "haben gewohnt",
      "habt gewohnt",
      "haben gewohnt",
    ],
    [
      "werde wohnen",
      "wirst wohnen",
      "wird wohnen",
      "werden wohnen",
      "werdet wohnen",
      "werden wohnen",
    ],
    ["wohnte", "wohntest", "wohnte", "wohnten", "wohntet", "wohnten"],
  ),
  deVerb(
    "verstehen",
    "to understand",
    "strong",
    36,
    ["common"],
    ["verstehe", "verstehst", "versteht", "verstehen", "versteht", "verstehen"],
    [
      "verstand",
      "verstandest",
      "verstand",
      "verstanden",
      "verstandet",
      "verstanden",
    ],
    [
      "habe verstanden",
      "hast verstanden",
      "hat verstanden",
      "haben verstanden",
      "habt verstanden",
      "haben verstanden",
    ],
    [
      "werde verstehen",
      "wirst verstehen",
      "wird verstehen",
      "werden verstehen",
      "werdet verstehen",
      "werden verstehen",
    ],
    [
      "verstände",
      "verständest",
      "verstände",
      "verständen",
      "verständet",
      "verständen",
    ],
    {
      preterite:
        "Strong verb (inseparable prefix ver-): vowel change eh→a: verstand",
    },
  ),
  deVerb(
    "beginnen",
    "to begin",
    "strong",
    37,
    ["common"],
    ["beginne", "beginnst", "beginnt", "beginnen", "beginnt", "beginnen"],
    ["begann", "begannst", "begann", "begannen", "begannt", "begannen"],
    [
      "habe begonnen",
      "hast begonnen",
      "hat begonnen",
      "haben begonnen",
      "habt begonnen",
      "haben begonnen",
    ],
    [
      "werde beginnen",
      "wirst beginnen",
      "wird beginnen",
      "werden beginnen",
      "werdet beginnen",
      "werden beginnen",
    ],
    ["begänne", "begännest", "begänne", "begännen", "begännet", "begännen"],
    {
      preterite: "Strong verb: vowel change i→a: begann",
      perfect: "Past participle: begonnen (i→o)",
    },
  ),
  deVerb(
    "öffnen",
    "to open",
    "weak",
    38,
    ["common"],
    ["öffne", "öffnest", "öffnet", "öffnen", "öffnet", "öffnen"],
    ["öffnete", "öffnetest", "öffnete", "öffneten", "öffnetet", "öffneten"],
    [
      "habe geöffnet",
      "hast geöffnet",
      "hat geöffnet",
      "haben geöffnet",
      "habt geöffnet",
      "haben geöffnet",
    ],
    [
      "werde öffnen",
      "wirst öffnen",
      "wird öffnen",
      "werden öffnen",
      "werdet öffnen",
      "werden öffnen",
    ],
    ["öffnete", "öffnetest", "öffnete", "öffneten", "öffnetet", "öffneten"],
    { present: "Weak verb with -e- insertion: du öffnest, er öffnet" },
  ),
  deVerb(
    "schließen",
    "to close",
    "strong",
    39,
    ["common"],
    ["schließe", "schließt", "schließt", "schließen", "schließt", "schließen"],
    ["schloss", "schlossest", "schloss", "schlossen", "schlosst", "schlossen"],
    [
      "habe geschlossen",
      "hast geschlossen",
      "hat geschlossen",
      "haben geschlossen",
      "habt geschlossen",
      "haben geschlossen",
    ],
    [
      "werde schließen",
      "wirst schließen",
      "wird schließen",
      "werden schließen",
      "werdet schließen",
      "werden schließen",
    ],
    [
      "schlösse",
      "schlössest",
      "schlösse",
      "schlössen",
      "schlösset",
      "schlössen",
    ],
    { preterite: "Strong verb: vowel change ie→o: schloss" },
  ),
  deVerb(
    "fragen",
    "to ask",
    "weak",
    40,
    ["common"],
    ["frage", "fragst", "fragt", "fragen", "fragt", "fragen"],
    ["fragte", "fragtest", "fragte", "fragten", "fragtet", "fragten"],
    [
      "habe gefragt",
      "hast gefragt",
      "hat gefragt",
      "haben gefragt",
      "habt gefragt",
      "haben gefragt",
    ],
    [
      "werde fragen",
      "wirst fragen",
      "wird fragen",
      "werden fragen",
      "werdet fragen",
      "werden fragen",
    ],
    ["fragte", "fragtest", "fragte", "fragten", "fragtet", "fragten"],
  ),
  deVerb(
    "antworten",
    "to answer",
    "weak",
    41,
    ["common"],
    [
      "antworte",
      "antwortest",
      "antwortet",
      "antworten",
      "antwortet",
      "antworten",
    ],
    [
      "antwortete",
      "antwortetest",
      "antwortete",
      "antworteten",
      "antwortetet",
      "antworteten",
    ],
    [
      "habe geantwortet",
      "hast geantwortet",
      "hat geantwortet",
      "haben geantwortet",
      "habt geantwortet",
      "haben geantwortet",
    ],
    [
      "werde antworten",
      "wirst antworten",
      "wird antworten",
      "werden antworten",
      "werdet antworten",
      "werden antworten",
    ],
    [
      "antwortete",
      "antwortetest",
      "antwortete",
      "antworteten",
      "antwortetet",
      "antworteten",
    ],
    { present: "Weak verb with -e- insertion before consonant endings" },
  ),
  deVerb(
    "lernen",
    "to learn",
    "weak",
    42,
    ["common"],
    ["lerne", "lernst", "lernt", "lernen", "lernt", "lernen"],
    ["lernte", "lerntest", "lernte", "lernten", "lerntet", "lernten"],
    [
      "habe gelernt",
      "hast gelernt",
      "hat gelernt",
      "haben gelernt",
      "habt gelernt",
      "haben gelernt",
    ],
    [
      "werde lernen",
      "wirst lernen",
      "wird lernen",
      "werden lernen",
      "werdet lernen",
      "werden lernen",
    ],
    ["lernte", "lerntest", "lernte", "lernten", "lerntet", "lernten"],
  ),
  deVerb(
    "spielen",
    "to play",
    "weak",
    43,
    ["common"],
    ["spiele", "spielst", "spielt", "spielen", "spielt", "spielen"],
    ["spielte", "spieltest", "spielte", "spielten", "spieltet", "spielten"],
    [
      "habe gespielt",
      "hast gespielt",
      "hat gespielt",
      "haben gespielt",
      "habt gespielt",
      "haben gespielt",
    ],
    [
      "werde spielen",
      "wirst spielen",
      "wird spielen",
      "werden spielen",
      "werdet spielen",
      "werden spielen",
    ],
    ["spielte", "spieltest", "spielte", "spielten", "spieltet", "spielten"],
  ),
  deVerb(
    "laufen",
    "to run, to walk",
    "strong",
    44,
    ["common"],
    ["laufe", "läufst", "läuft", "laufen", "lauft", "laufen"],
    ["lief", "liefst", "lief", "liefen", "lieft", "liefen"],
    [
      "bin gelaufen",
      "bist gelaufen",
      "ist gelaufen",
      "sind gelaufen",
      "seid gelaufen",
      "sind gelaufen",
    ],
    [
      "werde laufen",
      "wirst laufen",
      "wird laufen",
      "werden laufen",
      "werdet laufen",
      "werden laufen",
    ],
    ["liefe", "liefest", "liefe", "liefen", "liefet", "liefen"],
    {
      present: "Strong verb: vowel change au→äu in 2sg/3sg: läufst, läuft",
      perfect: "Uses sein (verb of motion): bin gelaufen",
    },
  ),
  deVerb(
    "helfen",
    "to help",
    "strong",
    45,
    ["common"],
    ["helfe", "hilfst", "hilft", "helfen", "helft", "helfen"],
    ["half", "halfst", "half", "halfen", "halft", "halfen"],
    [
      "habe geholfen",
      "hast geholfen",
      "hat geholfen",
      "haben geholfen",
      "habt geholfen",
      "haben geholfen",
    ],
    [
      "werde helfen",
      "wirst helfen",
      "wird helfen",
      "werden helfen",
      "werdet helfen",
      "werden helfen",
    ],
    ["hülfe", "hülfest", "hülfe", "hülfen", "hülfet", "hülfen"],
    { present: "Strong verb: vowel change e→i in 2sg/3sg: hilfst, hilft" },
  ),
  deVerb(
    "brauchen",
    "to need",
    "weak",
    46,
    ["common"],
    ["brauche", "brauchst", "braucht", "brauchen", "braucht", "brauchen"],
    [
      "brauchte",
      "brauchtest",
      "brauchte",
      "brauchten",
      "brauchtet",
      "brauchten",
    ],
    [
      "habe gebraucht",
      "hast gebraucht",
      "hat gebraucht",
      "haben gebraucht",
      "habt gebraucht",
      "haben gebraucht",
    ],
    [
      "werde brauchen",
      "wirst brauchen",
      "wird brauchen",
      "werden brauchen",
      "werdet brauchen",
      "werden brauchen",
    ],
    [
      "brauchte",
      "brauchtest",
      "brauchte",
      "brauchten",
      "brauchtet",
      "brauchten",
    ],
  ),
  deVerb(
    "warten",
    "to wait",
    "weak",
    47,
    ["common"],
    ["warte", "wartest", "wartet", "warten", "wartet", "warten"],
    ["wartete", "wartetest", "wartete", "warteten", "wartetet", "warteten"],
    [
      "habe gewartet",
      "hast gewartet",
      "hat gewartet",
      "haben gewartet",
      "habt gewartet",
      "haben gewartet",
    ],
    [
      "werde warten",
      "wirst warten",
      "wird warten",
      "werden warten",
      "werdet warten",
      "werden warten",
    ],
    ["wartete", "wartetest", "wartete", "warteten", "wartetet", "warteten"],
    { present: "Weak verb with -e- insertion: du wartest, er wartet" },
  ),
  deVerb(
    "fallen",
    "to fall",
    "strong",
    48,
    ["common"],
    ["falle", "fällst", "fällt", "fallen", "fallt", "fallen"],
    ["fiel", "fielst", "fiel", "fielen", "fielt", "fielen"],
    [
      "bin gefallen",
      "bist gefallen",
      "ist gefallen",
      "sind gefallen",
      "seid gefallen",
      "sind gefallen",
    ],
    [
      "werde fallen",
      "wirst fallen",
      "wird fallen",
      "werden fallen",
      "werdet fallen",
      "werden fallen",
    ],
    ["fiele", "fielest", "fiele", "fielen", "fielet", "fielen"],
    {
      present: "Strong verb: vowel change a→ä in 2sg/3sg: fällst, fällt",
      perfect: "Uses sein (verb of motion): bin gefallen",
    },
  ),
  deVerb(
    "tragen",
    "to carry, to wear",
    "strong",
    49,
    ["common"],
    ["trage", "trägst", "trägt", "tragen", "tragt", "tragen"],
    ["trug", "trugst", "trug", "trugen", "trugt", "trugen"],
    [
      "habe getragen",
      "hast getragen",
      "hat getragen",
      "haben getragen",
      "habt getragen",
      "haben getragen",
    ],
    [
      "werde tragen",
      "wirst tragen",
      "wird tragen",
      "werden tragen",
      "werdet tragen",
      "werden tragen",
    ],
    ["trüge", "trügest", "trüge", "trügen", "trüget", "trügen"],
    { present: "Strong verb: vowel change a→ä in 2sg/3sg: trägst, trägt" },
  ),
  deVerb(
    "liegen",
    "to lie (position)",
    "strong",
    50,
    ["common"],
    ["liege", "liegst", "liegt", "liegen", "liegt", "liegen"],
    ["lag", "lagst", "lag", "lagen", "lagt", "lagen"],
    [
      "habe gelegen",
      "hast gelegen",
      "hat gelegen",
      "haben gelegen",
      "habt gelegen",
      "haben gelegen",
    ],
    [
      "werde liegen",
      "wirst liegen",
      "wird liegen",
      "werden liegen",
      "werdet liegen",
      "werden liegen",
    ],
    ["läge", "lägest", "läge", "lägen", "läget", "lägen"],
    { preterite: "Strong verb: vowel change ie→a: lag" },
  ),
];

// ========================================================================
// French verbs helper
// ========================================================================
function frVerb(
  infinitive: string,
  english: string,
  verbClass: string,
  rank: number,
  tags: string[],
  present: [string, string, string, string, string, string],
  imperfect: [string, string, string, string, string, string],
  perfect: [string, string, string, string, string, string],
  future: [string, string, string, string, string, string],
  conditional: [string, string, string, string, string, string],
  explanations?: Partial<Record<string, string>>,
): VerbSeedData {
  const pronouns = ["je", "tu", "il/elle", "nous", "vous", "ils/elles"];
  const keys = ["1sg", "2sg", "3sg", "1pl", "2pl", "3pl"] as const;

  const forms: VerbSeedData["forms"] = [];

  const addForms = (
    tense: string,
    mood: string,
    conjugations: string[],
    explanationKey?: string,
  ) => {
    conjugations.forEach((form, i) => {
      forms.push({
        tense,
        mood,
        pronoun: pronouns[i],
        pronoun_key: keys[i],
        conjugated_form: form,
        rule_explanation: explanationKey
          ? explanations?.[explanationKey]
          : undefined,
      });
    });
  };

  addForms("present", "indicative", [...present], "present");
  addForms("imperfect", "indicative", [...imperfect], "imperfect");
  addForms("perfect", "indicative", [...perfect], "perfect");
  addForms("future", "indicative", [...future], "future");
  addForms("conditional", "indicative", [...conditional], "conditional");

  return {
    language: "fr",
    infinitive,
    english_meaning: english,
    verb_class: verbClass,
    frequency_rank: rank,
    tags,
    forms,
  };
}

export const FRENCH_VERBS: VerbSeedData[] = [
  frVerb(
    "être",
    "to be",
    "irregular",
    1,
    ["common", "auxiliary"],
    ["suis", "es", "est", "sommes", "êtes", "sont"],
    ["étais", "étais", "était", "étions", "étiez", "étaient"],
    ["ai été", "as été", "a été", "avons été", "avez été", "ont été"],
    ["serai", "seras", "sera", "serons", "serez", "seront"],
    ["serais", "serais", "serait", "serions", "seriez", "seraient"],
    {
      present: "Highly irregular — all forms must be memorised",
      future: "Irregular future stem: ser-",
    },
  ),
  frVerb(
    "avoir",
    "to have",
    "irregular",
    2,
    ["common", "auxiliary"],
    ["ai", "as", "a", "avons", "avez", "ont"],
    ["avais", "avais", "avait", "avions", "aviez", "avaient"],
    ["ai eu", "as eu", "a eu", "avons eu", "avez eu", "ont eu"],
    ["aurai", "auras", "aura", "aurons", "aurez", "auront"],
    ["aurais", "aurais", "aurait", "aurions", "auriez", "auraient"],
    {
      present: "Highly irregular — all forms must be memorised",
      future: "Irregular future stem: aur-",
    },
  ),
  frVerb(
    "faire",
    "to do, to make",
    "irregular",
    3,
    ["common"],
    ["fais", "fais", "fait", "faisons", "faites", "font"],
    ["faisais", "faisais", "faisait", "faisions", "faisiez", "faisaient"],
    ["ai fait", "as fait", "a fait", "avons fait", "avez fait", "ont fait"],
    ["ferai", "feras", "fera", "ferons", "ferez", "feront"],
    ["ferais", "ferais", "ferait", "ferions", "feriez", "feraient"],
    {
      present: "Irregular: vous faites (not *faisez), ils font",
      future: "Irregular future stem: fer-",
    },
  ),
  frVerb(
    "aller",
    "to go",
    "irregular",
    4,
    ["common"],
    ["vais", "vas", "va", "allons", "allez", "vont"],
    ["allais", "allais", "allait", "allions", "alliez", "allaient"],
    [
      "suis allé(e)",
      "es allé(e)",
      "est allé(e)",
      "sommes allé(e)s",
      "êtes allé(e)s",
      "sont allé(e)s",
    ],
    ["irai", "iras", "ira", "irons", "irez", "iront"],
    ["irais", "irais", "irait", "irions", "iriez", "iraient"],
    {
      present: "Highly irregular: 3 different stems (va-/all-/v-)",
      perfect: "Uses être as auxiliary: suis allé(e)",
      future: "Irregular future stem: ir-",
    },
  ),
  frVerb(
    "pouvoir",
    "to be able to, can",
    "irregular",
    5,
    ["common"],
    ["peux", "peux", "peut", "pouvons", "pouvez", "peuvent"],
    ["pouvais", "pouvais", "pouvait", "pouvions", "pouviez", "pouvaient"],
    ["ai pu", "as pu", "a pu", "avons pu", "avez pu", "ont pu"],
    ["pourrai", "pourras", "pourra", "pourrons", "pourrez", "pourront"],
    ["pourrais", "pourrais", "pourrait", "pourrions", "pourriez", "pourraient"],
    {
      present: "Irregular: stem changes peuv-/pouv-/peuv-",
      future: "Irregular future stem: pourr- (double r)",
    },
  ),
  frVerb(
    "vouloir",
    "to want",
    "irregular",
    6,
    ["common"],
    ["veux", "veux", "veut", "voulons", "voulez", "veulent"],
    ["voulais", "voulais", "voulait", "voulions", "vouliez", "voulaient"],
    [
      "ai voulu",
      "as voulu",
      "a voulu",
      "avons voulu",
      "avez voulu",
      "ont voulu",
    ],
    ["voudrai", "voudras", "voudra", "voudrons", "voudrez", "voudront"],
    ["voudrais", "voudrais", "voudrait", "voudrions", "voudriez", "voudraient"],
    {
      present: "Irregular: stem changes veu-/voul-/veul-",
      future: "Irregular future stem: voudr-",
    },
  ),
  frVerb(
    "devoir",
    "to have to, must",
    "irregular",
    7,
    ["common"],
    ["dois", "dois", "doit", "devons", "devez", "doivent"],
    ["devais", "devais", "devait", "devions", "deviez", "devaient"],
    ["ai dû", "as dû", "a dû", "avons dû", "avez dû", "ont dû"],
    ["devrai", "devras", "devra", "devrons", "devrez", "devront"],
    ["devrais", "devrais", "devrait", "devrions", "devriez", "devraient"],
    {
      present: "Irregular: stem changes doi-/dev-/doiv-",
      perfect: "Past participle dû has circumflex accent",
    },
  ),
  frVerb(
    "dire",
    "to say, to tell",
    "irregular",
    8,
    ["common"],
    ["dis", "dis", "dit", "disons", "dites", "disent"],
    ["disais", "disais", "disait", "disions", "disiez", "disaient"],
    ["ai dit", "as dit", "a dit", "avons dit", "avez dit", "ont dit"],
    ["dirai", "diras", "dira", "dirons", "direz", "diront"],
    ["dirais", "dirais", "dirait", "dirions", "diriez", "diraient"],
    { present: "Irregular: vous dites (not *disez)" },
  ),
  frVerb(
    "savoir",
    "to know (a fact)",
    "irregular",
    9,
    ["common"],
    ["sais", "sais", "sait", "savons", "savez", "savent"],
    ["savais", "savais", "savait", "savions", "saviez", "savaient"],
    ["ai su", "as su", "a su", "avons su", "avez su", "ont su"],
    ["saurai", "sauras", "saura", "saurons", "saurez", "sauront"],
    ["saurais", "saurais", "saurait", "saurions", "sauriez", "sauraient"],
    {
      present: "Irregular: sai-/sav- stem alternation",
      future: "Irregular future stem: saur-",
    },
  ),
  frVerb(
    "voir",
    "to see",
    "irregular",
    10,
    ["common"],
    ["vois", "vois", "voit", "voyons", "voyez", "voient"],
    ["voyais", "voyais", "voyait", "voyions", "voyiez", "voyaient"],
    ["ai vu", "as vu", "a vu", "avons vu", "avez vu", "ont vu"],
    ["verrai", "verras", "verra", "verrons", "verrez", "verront"],
    ["verrais", "verrais", "verrait", "verrions", "verriez", "verraient"],
    {
      present: "Irregular: voi-/voy- stem alternation",
      future: "Irregular future stem: verr- (double r)",
    },
  ),
  frVerb(
    "venir",
    "to come",
    "irregular",
    11,
    ["common"],
    ["viens", "viens", "vient", "venons", "venez", "viennent"],
    ["venais", "venais", "venait", "venions", "veniez", "venaient"],
    [
      "suis venu(e)",
      "es venu(e)",
      "est venu(e)",
      "sommes venu(e)s",
      "êtes venu(e)s",
      "sont venu(e)s",
    ],
    ["viendrai", "viendras", "viendra", "viendrons", "viendrez", "viendront"],
    [
      "viendrais",
      "viendrais",
      "viendrait",
      "viendrions",
      "viendriez",
      "viendraient",
    ],
    {
      present: "Irregular: vien-/ven-/vienn- stem alternation",
      perfect: "Uses être: suis venu(e)",
      future: "Irregular future stem: viendr-",
    },
  ),
  frVerb(
    "prendre",
    "to take",
    "irregular",
    12,
    ["common"],
    ["prends", "prends", "prend", "prenons", "prenez", "prennent"],
    ["prenais", "prenais", "prenait", "prenions", "preniez", "prenaient"],
    ["ai pris", "as pris", "a pris", "avons pris", "avez pris", "ont pris"],
    ["prendrai", "prendras", "prendra", "prendrons", "prendrez", "prendront"],
    [
      "prendrais",
      "prendrais",
      "prendrait",
      "prendrions",
      "prendriez",
      "prendraient",
    ],
    { present: "Irregular: prend-/pren-/prenn- stem alternation" },
  ),
  frVerb(
    "donner",
    "to give",
    "regular_er",
    13,
    ["common"],
    ["donne", "donnes", "donne", "donnons", "donnez", "donnent"],
    ["donnais", "donnais", "donnait", "donnions", "donniez", "donnaient"],
    [
      "ai donné",
      "as donné",
      "a donné",
      "avons donné",
      "avez donné",
      "ont donné",
    ],
    ["donnerai", "donneras", "donnera", "donnerons", "donnerez", "donneront"],
    [
      "donnerais",
      "donnerais",
      "donnerait",
      "donnerions",
      "donneriez",
      "donneraient",
    ],
  ),
  frVerb(
    "parler",
    "to speak",
    "regular_er",
    14,
    ["common"],
    ["parle", "parles", "parle", "parlons", "parlez", "parlent"],
    ["parlais", "parlais", "parlait", "parlions", "parliez", "parlaient"],
    [
      "ai parlé",
      "as parlé",
      "a parlé",
      "avons parlé",
      "avez parlé",
      "ont parlé",
    ],
    ["parlerai", "parleras", "parlera", "parlerons", "parlerez", "parleront"],
    [
      "parlerais",
      "parlerais",
      "parlerait",
      "parlerions",
      "parleriez",
      "parleraient",
    ],
  ),
  frVerb(
    "mettre",
    "to put",
    "irregular",
    15,
    ["common"],
    ["mets", "mets", "met", "mettons", "mettez", "mettent"],
    ["mettais", "mettais", "mettait", "mettions", "mettiez", "mettaient"],
    ["ai mis", "as mis", "a mis", "avons mis", "avez mis", "ont mis"],
    ["mettrai", "mettras", "mettra", "mettrons", "mettrez", "mettront"],
    ["mettrais", "mettrais", "mettrait", "mettrions", "mettriez", "mettraient"],
    {
      present: "Irregular: 3sg drops one -t: il met",
      perfect: "Irregular past participle: mis",
    },
  ),
  frVerb(
    "partir",
    "to leave",
    "irregular",
    16,
    ["common"],
    ["pars", "pars", "part", "partons", "partez", "partent"],
    ["partais", "partais", "partait", "partions", "partiez", "partaient"],
    [
      "suis parti(e)",
      "es parti(e)",
      "est parti(e)",
      "sommes parti(e)s",
      "êtes parti(e)s",
      "sont parti(e)s",
    ],
    ["partirai", "partiras", "partira", "partirons", "partirez", "partiront"],
    [
      "partirais",
      "partirais",
      "partirait",
      "partirions",
      "partiriez",
      "partiraient",
    ],
    {
      present: "Irregular -ir: par-/part- stem alternation",
      perfect: "Uses être: suis parti(e)",
    },
  ),
  frVerb(
    "croire",
    "to believe",
    "irregular",
    17,
    ["common"],
    ["crois", "crois", "croit", "croyons", "croyez", "croient"],
    ["croyais", "croyais", "croyait", "croyions", "croyiez", "croyaient"],
    ["ai cru", "as cru", "a cru", "avons cru", "avez cru", "ont cru"],
    ["croirai", "croiras", "croira", "croirons", "croirez", "croiront"],
    ["croirais", "croirais", "croirait", "croirions", "croiriez", "croiraient"],
    { present: "Irregular: croi-/croy-/croi- stem alternation" },
  ),
  frVerb(
    "trouver",
    "to find",
    "regular_er",
    18,
    ["common"],
    ["trouve", "trouves", "trouve", "trouvons", "trouvez", "trouvent"],
    ["trouvais", "trouvais", "trouvait", "trouvions", "trouviez", "trouvaient"],
    [
      "ai trouvé",
      "as trouvé",
      "a trouvé",
      "avons trouvé",
      "avez trouvé",
      "ont trouvé",
    ],
    [
      "trouverai",
      "trouveras",
      "trouvera",
      "trouverons",
      "trouverez",
      "trouveront",
    ],
    [
      "trouverais",
      "trouverais",
      "trouverait",
      "trouverions",
      "trouveriez",
      "trouveraient",
    ],
  ),
  frVerb(
    "penser",
    "to think",
    "regular_er",
    19,
    ["common"],
    ["pense", "penses", "pense", "pensons", "pensez", "pensent"],
    ["pensais", "pensais", "pensait", "pensions", "pensiez", "pensaient"],
    [
      "ai pensé",
      "as pensé",
      "a pensé",
      "avons pensé",
      "avez pensé",
      "ont pensé",
    ],
    ["penserai", "penseras", "pensera", "penserons", "penserez", "penseront"],
    [
      "penserais",
      "penserais",
      "penserait",
      "penserions",
      "penseriez",
      "penseraient",
    ],
  ),
  frVerb(
    "connaître",
    "to know (a person/place)",
    "irregular",
    20,
    ["common"],
    [
      "connais",
      "connais",
      "connaît",
      "connaissons",
      "connaissez",
      "connaissent",
    ],
    [
      "connaissais",
      "connaissais",
      "connaissait",
      "connaissions",
      "connaissiez",
      "connaissaient",
    ],
    [
      "ai connu",
      "as connu",
      "a connu",
      "avons connu",
      "avez connu",
      "ont connu",
    ],
    [
      "connaîtrai",
      "connaîtras",
      "connaîtra",
      "connaîtrons",
      "connaîtrez",
      "connaîtront",
    ],
    [
      "connaîtrais",
      "connaîtrais",
      "connaîtrait",
      "connaîtrions",
      "connaîtriez",
      "connaîtraient",
    ],
    { present: "Irregular: connai-/connaiss- stem alternation; î before t" },
  ),
  frVerb(
    "aimer",
    "to love, to like",
    "regular_er",
    21,
    ["common"],
    ["aime", "aimes", "aime", "aimons", "aimez", "aiment"],
    ["aimais", "aimais", "aimait", "aimions", "aimiez", "aimaient"],
    ["ai aimé", "as aimé", "a aimé", "avons aimé", "avez aimé", "ont aimé"],
    ["aimerai", "aimeras", "aimera", "aimerons", "aimerez", "aimeront"],
    ["aimerais", "aimerais", "aimerait", "aimerions", "aimeriez", "aimeraient"],
  ),
  frVerb(
    "manger",
    "to eat",
    "regular_er",
    22,
    ["common"],
    ["mange", "manges", "mange", "mangeons", "mangez", "mangent"],
    ["mangeais", "mangeais", "mangeait", "mangions", "mangiez", "mangeaient"],
    [
      "ai mangé",
      "as mangé",
      "a mangé",
      "avons mangé",
      "avez mangé",
      "ont mangé",
    ],
    ["mangerai", "mangeras", "mangera", "mangerons", "mangerez", "mangeront"],
    [
      "mangerais",
      "mangerais",
      "mangerait",
      "mangerions",
      "mangeriez",
      "mangeraient",
    ],
    { present: "Spelling change: nous mangeons (e inserted to keep soft g)" },
  ),
  frVerb(
    "boire",
    "to drink",
    "irregular",
    23,
    ["common"],
    ["bois", "bois", "boit", "buvons", "buvez", "boivent"],
    ["buvais", "buvais", "buvait", "buvions", "buviez", "buvaient"],
    ["ai bu", "as bu", "a bu", "avons bu", "avez bu", "ont bu"],
    ["boirai", "boiras", "boira", "boirons", "boirez", "boiront"],
    ["boirais", "boirais", "boirait", "boirions", "boiriez", "boiraient"],
    { present: "Irregular: boi-/buv-/boiv- stem alternation" },
  ),
  frVerb(
    "écrire",
    "to write",
    "irregular",
    24,
    ["common"],
    ["écris", "écris", "écrit", "écrivons", "écrivez", "écrivent"],
    ["écrivais", "écrivais", "écrivait", "écrivions", "écriviez", "écrivaient"],
    [
      "ai écrit",
      "as écrit",
      "a écrit",
      "avons écrit",
      "avez écrit",
      "ont écrit",
    ],
    ["écrirai", "écriras", "écrira", "écrirons", "écrirez", "écriront"],
    ["écrirais", "écrirais", "écrirait", "écririons", "écririez", "écriraient"],
    { present: "Irregular: écri-/écriv- stem alternation" },
  ),
  frVerb(
    "lire",
    "to read",
    "irregular",
    25,
    ["common"],
    ["lis", "lis", "lit", "lisons", "lisez", "lisent"],
    ["lisais", "lisais", "lisait", "lisions", "lisiez", "lisaient"],
    ["ai lu", "as lu", "a lu", "avons lu", "avez lu", "ont lu"],
    ["lirai", "liras", "lira", "lirons", "lirez", "liront"],
    ["lirais", "lirais", "lirait", "lirions", "liriez", "liraient"],
    { perfect: "Irregular past participle: lu" },
  ),
  frVerb(
    "entendre",
    "to hear",
    "regular_re",
    26,
    ["common"],
    ["entends", "entends", "entend", "entendons", "entendez", "entendent"],
    [
      "entendais",
      "entendais",
      "entendait",
      "entendions",
      "entendiez",
      "entendaient",
    ],
    [
      "ai entendu",
      "as entendu",
      "a entendu",
      "avons entendu",
      "avez entendu",
      "ont entendu",
    ],
    [
      "entendrai",
      "entendras",
      "entendra",
      "entendrons",
      "entendrez",
      "entendront",
    ],
    [
      "entendrais",
      "entendrais",
      "entendrait",
      "entendrions",
      "entendriez",
      "entendraient",
    ],
  ),
  frVerb(
    "attendre",
    "to wait",
    "regular_re",
    27,
    ["common"],
    ["attends", "attends", "attend", "attendons", "attendez", "attendent"],
    [
      "attendais",
      "attendais",
      "attendait",
      "attendions",
      "attendiez",
      "attendaient",
    ],
    [
      "ai attendu",
      "as attendu",
      "a attendu",
      "avons attendu",
      "avez attendu",
      "ont attendu",
    ],
    [
      "attendrai",
      "attendras",
      "attendra",
      "attendrons",
      "attendrez",
      "attendront",
    ],
    [
      "attendrais",
      "attendrais",
      "attendrait",
      "attendrions",
      "attendriez",
      "attendraient",
    ],
  ),
  frVerb(
    "comprendre",
    "to understand",
    "irregular",
    28,
    ["common"],
    [
      "comprends",
      "comprends",
      "comprend",
      "comprenons",
      "comprenez",
      "comprennent",
    ],
    [
      "comprenais",
      "comprenais",
      "comprenait",
      "comprenions",
      "compreniez",
      "comprenaient",
    ],
    [
      "ai compris",
      "as compris",
      "a compris",
      "avons compris",
      "avez compris",
      "ont compris",
    ],
    [
      "comprendrai",
      "comprendras",
      "comprendra",
      "comprendrons",
      "comprendrez",
      "comprendront",
    ],
    [
      "comprendrais",
      "comprendrais",
      "comprendrait",
      "comprendrions",
      "comprendriez",
      "comprendraient",
    ],
    { present: "Conjugates like prendre: comprend-/compren-/comprenn-" },
  ),
  frVerb(
    "rester",
    "to stay",
    "regular_er",
    29,
    ["common"],
    ["reste", "restes", "reste", "restons", "restez", "restent"],
    ["restais", "restais", "restait", "restions", "restiez", "restaient"],
    [
      "suis resté(e)",
      "es resté(e)",
      "est resté(e)",
      "sommes resté(e)s",
      "êtes resté(e)s",
      "sont resté(e)s",
    ],
    ["resterai", "resteras", "restera", "resterons", "resterez", "resteront"],
    [
      "resterais",
      "resterais",
      "resterait",
      "resterions",
      "resteriez",
      "resteraient",
    ],
    { perfect: "Uses être: suis resté(e)" },
  ),
  frVerb(
    "vivre",
    "to live",
    "irregular",
    30,
    ["common"],
    ["vis", "vis", "vit", "vivons", "vivez", "vivent"],
    ["vivais", "vivais", "vivait", "vivions", "viviez", "vivaient"],
    ["ai vécu", "as vécu", "a vécu", "avons vécu", "avez vécu", "ont vécu"],
    ["vivrai", "vivras", "vivra", "vivrons", "vivrez", "vivront"],
    ["vivrais", "vivrais", "vivrait", "vivrions", "vivriez", "vivraient"],
    { perfect: "Irregular past participle: vécu" },
  ),
  frVerb(
    "finir",
    "to finish",
    "regular_ir",
    31,
    ["common"],
    ["finis", "finis", "finit", "finissons", "finissez", "finissent"],
    [
      "finissais",
      "finissais",
      "finissait",
      "finissions",
      "finissiez",
      "finissaient",
    ],
    ["ai fini", "as fini", "a fini", "avons fini", "avez fini", "ont fini"],
    ["finirai", "finiras", "finira", "finirons", "finirez", "finiront"],
    ["finirais", "finirais", "finirait", "finirions", "finiriez", "finiraient"],
  ),
  frVerb(
    "choisir",
    "to choose",
    "regular_ir",
    32,
    ["common"],
    [
      "choisis",
      "choisis",
      "choisit",
      "choisissons",
      "choisissez",
      "choisissent",
    ],
    [
      "choisissais",
      "choisissais",
      "choisissait",
      "choisissions",
      "choisissiez",
      "choisissaient",
    ],
    [
      "ai choisi",
      "as choisi",
      "a choisi",
      "avons choisi",
      "avez choisi",
      "ont choisi",
    ],
    [
      "choisirai",
      "choisiras",
      "choisira",
      "choisirons",
      "choisirez",
      "choisiront",
    ],
    [
      "choisirais",
      "choisirais",
      "choisirait",
      "choisirions",
      "choisiriez",
      "choisiraient",
    ],
  ),
  frVerb(
    "répondre",
    "to answer",
    "regular_re",
    33,
    ["common"],
    ["réponds", "réponds", "répond", "répondons", "répondez", "répondent"],
    [
      "répondais",
      "répondais",
      "répondait",
      "répondions",
      "répondiez",
      "répondaient",
    ],
    [
      "ai répondu",
      "as répondu",
      "a répondu",
      "avons répondu",
      "avez répondu",
      "ont répondu",
    ],
    [
      "répondrai",
      "répondras",
      "répondra",
      "répondrons",
      "répondrez",
      "répondront",
    ],
    [
      "répondrais",
      "répondrais",
      "répondrait",
      "répondrions",
      "répondriez",
      "répondraient",
    ],
  ),
  frVerb(
    "acheter",
    "to buy",
    "regular_er",
    34,
    ["common"],
    ["achète", "achètes", "achète", "achetons", "achetez", "achètent"],
    ["achetais", "achetais", "achetait", "achetions", "achetiez", "achetaient"],
    [
      "ai acheté",
      "as acheté",
      "a acheté",
      "avons acheté",
      "avez acheté",
      "ont acheté",
    ],
    [
      "achèterai",
      "achèteras",
      "achètera",
      "achèterons",
      "achèterez",
      "achèteront",
    ],
    [
      "achèterais",
      "achèterais",
      "achèterait",
      "achèterions",
      "achèteriez",
      "achèteraient",
    ],
    { present: "Spelling change: e→è before silent ending (achète)" },
  ),
  frVerb(
    "jouer",
    "to play",
    "regular_er",
    35,
    ["common"],
    ["joue", "joues", "joue", "jouons", "jouez", "jouent"],
    ["jouais", "jouais", "jouait", "jouions", "jouiez", "jouaient"],
    ["ai joué", "as joué", "a joué", "avons joué", "avez joué", "ont joué"],
    ["jouerai", "joueras", "jouera", "jouerons", "jouerez", "joueront"],
    ["jouerais", "jouerais", "jouerait", "jouerions", "joueriez", "joueraient"],
  ),
  frVerb(
    "travailler",
    "to work",
    "regular_er",
    36,
    ["common"],
    [
      "travaille",
      "travailles",
      "travaille",
      "travaillons",
      "travaillez",
      "travaillent",
    ],
    [
      "travaillais",
      "travaillais",
      "travaillait",
      "travaillions",
      "travailliez",
      "travaillaient",
    ],
    [
      "ai travaillé",
      "as travaillé",
      "a travaillé",
      "avons travaillé",
      "avez travaillé",
      "ont travaillé",
    ],
    [
      "travaillerai",
      "travailleras",
      "travaillera",
      "travaillerons",
      "travaillerez",
      "travailleront",
    ],
    [
      "travaillerais",
      "travaillerais",
      "travaillerait",
      "travaillerions",
      "travailleriez",
      "travailleraient",
    ],
  ),
  frVerb(
    "apprendre",
    "to learn",
    "irregular",
    37,
    ["common"],
    ["apprends", "apprends", "apprend", "apprenons", "apprenez", "apprennent"],
    [
      "apprenais",
      "apprenais",
      "apprenait",
      "apprenions",
      "appreniez",
      "apprenaient",
    ],
    [
      "ai appris",
      "as appris",
      "a appris",
      "avons appris",
      "avez appris",
      "ont appris",
    ],
    [
      "apprendrai",
      "apprendras",
      "apprendra",
      "apprendrons",
      "apprendrez",
      "apprendront",
    ],
    [
      "apprendrais",
      "apprendrais",
      "apprendrait",
      "apprendrions",
      "apprendriez",
      "apprendraient",
    ],
    { present: "Conjugates like prendre" },
  ),
  frVerb(
    "habiter",
    "to live (reside)",
    "regular_er",
    38,
    ["common"],
    ["habite", "habites", "habite", "habitons", "habitez", "habitent"],
    ["habitais", "habitais", "habitait", "habitions", "habitiez", "habitaient"],
    [
      "ai habité",
      "as habité",
      "a habité",
      "avons habité",
      "avez habité",
      "ont habité",
    ],
    [
      "habiterai",
      "habiteras",
      "habitera",
      "habiterons",
      "habiterez",
      "habiteront",
    ],
    [
      "habiterais",
      "habiterais",
      "habiterait",
      "habiterions",
      "habiteriez",
      "habiteraient",
    ],
  ),
  frVerb(
    "ouvrir",
    "to open",
    "irregular",
    39,
    ["common"],
    ["ouvre", "ouvres", "ouvre", "ouvrons", "ouvrez", "ouvrent"],
    ["ouvrais", "ouvrais", "ouvrait", "ouvrions", "ouvriez", "ouvraient"],
    [
      "ai ouvert",
      "as ouvert",
      "a ouvert",
      "avons ouvert",
      "avez ouvert",
      "ont ouvert",
    ],
    ["ouvrirai", "ouvriras", "ouvrira", "ouvrirons", "ouvrirez", "ouvriront"],
    [
      "ouvrirais",
      "ouvrirais",
      "ouvrirait",
      "ouvririons",
      "ouvririez",
      "ouvriraient",
    ],
    {
      present: "Irregular -ir verb: conjugates like -er in present (ouvre)",
      perfect: "Irregular past participle: ouvert",
    },
  ),
  frVerb(
    "demander",
    "to ask",
    "regular_er",
    40,
    ["common"],
    ["demande", "demandes", "demande", "demandons", "demandez", "demandent"],
    [
      "demandais",
      "demandais",
      "demandait",
      "demandions",
      "demandiez",
      "demandaient",
    ],
    [
      "ai demandé",
      "as demandé",
      "a demandé",
      "avons demandé",
      "avez demandé",
      "ont demandé",
    ],
    [
      "demanderai",
      "demanderas",
      "demandera",
      "demanderons",
      "demanderez",
      "demanderont",
    ],
    [
      "demanderais",
      "demanderais",
      "demanderait",
      "demanderions",
      "demanderiez",
      "demanderaient",
    ],
  ),
  frVerb(
    "regarder",
    "to watch, to look at",
    "regular_er",
    41,
    ["common"],
    ["regarde", "regardes", "regarde", "regardons", "regardez", "regardent"],
    [
      "regardais",
      "regardais",
      "regardait",
      "regardions",
      "regardiez",
      "regardaient",
    ],
    [
      "ai regardé",
      "as regardé",
      "a regardé",
      "avons regardé",
      "avez regardé",
      "ont regardé",
    ],
    [
      "regarderai",
      "regarderas",
      "regardera",
      "regarderons",
      "regarderez",
      "regarderont",
    ],
    [
      "regarderais",
      "regarderais",
      "regarderait",
      "regarderions",
      "regarderiez",
      "regarderaient",
    ],
  ),
  frVerb(
    "montrer",
    "to show",
    "regular_er",
    42,
    ["common"],
    ["montre", "montres", "montre", "montrons", "montrez", "montrent"],
    ["montrais", "montrais", "montrait", "montrions", "montriez", "montraient"],
    [
      "ai montré",
      "as montré",
      "a montré",
      "avons montré",
      "avez montré",
      "ont montré",
    ],
    [
      "montrerai",
      "montreras",
      "montrera",
      "montrerons",
      "montrerez",
      "montreront",
    ],
    [
      "montrerais",
      "montrerais",
      "montrerait",
      "montrerions",
      "montreriez",
      "montreraient",
    ],
  ),
  frVerb(
    "porter",
    "to carry, to wear",
    "regular_er",
    43,
    ["common"],
    ["porte", "portes", "porte", "portons", "portez", "portent"],
    ["portais", "portais", "portait", "portions", "portiez", "portaient"],
    [
      "ai porté",
      "as porté",
      "a porté",
      "avons porté",
      "avez porté",
      "ont porté",
    ],
    ["porterai", "porteras", "portera", "porterons", "porterez", "porteront"],
    [
      "porterais",
      "porterais",
      "porterait",
      "porterions",
      "porteriez",
      "porteraient",
    ],
  ),
  frVerb(
    "arriver",
    "to arrive",
    "regular_er",
    44,
    ["common"],
    ["arrive", "arrives", "arrive", "arrivons", "arrivez", "arrivent"],
    ["arrivais", "arrivais", "arrivait", "arrivions", "arriviez", "arrivaient"],
    [
      "suis arrivé(e)",
      "es arrivé(e)",
      "est arrivé(e)",
      "sommes arrivé(e)s",
      "êtes arrivé(e)s",
      "sont arrivé(e)s",
    ],
    [
      "arriverai",
      "arriveras",
      "arrivera",
      "arriverons",
      "arriverez",
      "arriveront",
    ],
    [
      "arriverais",
      "arriverais",
      "arriverait",
      "arriverions",
      "arriveriez",
      "arriveraient",
    ],
    { perfect: "Uses être (verb of motion): suis arrivé(e)" },
  ),
  frVerb(
    "commencer",
    "to begin",
    "regular_er",
    45,
    ["common"],
    [
      "commence",
      "commences",
      "commence",
      "commençons",
      "commencez",
      "commencent",
    ],
    [
      "commençais",
      "commençais",
      "commençait",
      "commencions",
      "commenciez",
      "commençaient",
    ],
    [
      "ai commencé",
      "as commencé",
      "a commencé",
      "avons commencé",
      "avez commencé",
      "ont commencé",
    ],
    [
      "commencerai",
      "commenceras",
      "commencera",
      "commencerons",
      "commencerez",
      "commenceront",
    ],
    [
      "commencerais",
      "commencerais",
      "commencerait",
      "commencerions",
      "commenceriez",
      "commenceraient",
    ],
    { present: "Spelling change: nous commençons (ç to keep soft c)" },
  ),
  frVerb(
    "appeler",
    "to call",
    "regular_er",
    46,
    ["common"],
    ["appelle", "appelles", "appelle", "appelons", "appelez", "appellent"],
    ["appelais", "appelais", "appelait", "appelions", "appeliez", "appelaient"],
    [
      "ai appelé",
      "as appelé",
      "a appelé",
      "avons appelé",
      "avez appelé",
      "ont appelé",
    ],
    [
      "appellerai",
      "appelleras",
      "appellera",
      "appellerons",
      "appellerez",
      "appelleront",
    ],
    [
      "appellerais",
      "appellerais",
      "appellerait",
      "appellerions",
      "appelleriez",
      "appelleraient",
    ],
    { present: "Spelling change: l→ll before silent ending (appelle)" },
  ),
  frVerb(
    "tomber",
    "to fall",
    "regular_er",
    47,
    ["common"],
    ["tombe", "tombes", "tombe", "tombons", "tombez", "tombent"],
    ["tombais", "tombais", "tombait", "tombions", "tombiez", "tombaient"],
    [
      "suis tombé(e)",
      "es tombé(e)",
      "est tombé(e)",
      "sommes tombé(e)s",
      "êtes tombé(e)s",
      "sont tombé(e)s",
    ],
    ["tomberai", "tomberas", "tombera", "tomberons", "tomberez", "tomberont"],
    [
      "tomberais",
      "tomberais",
      "tomberait",
      "tomberions",
      "tomberiez",
      "tomberaient",
    ],
    { perfect: "Uses être (verb of motion): suis tombé(e)" },
  ),
  frVerb(
    "sortir",
    "to go out",
    "irregular",
    48,
    ["common"],
    ["sors", "sors", "sort", "sortons", "sortez", "sortent"],
    ["sortais", "sortais", "sortait", "sortions", "sortiez", "sortaient"],
    [
      "suis sorti(e)",
      "es sorti(e)",
      "est sorti(e)",
      "sommes sorti(e)s",
      "êtes sorti(e)s",
      "sont sorti(e)s",
    ],
    ["sortirai", "sortiras", "sortira", "sortirons", "sortirez", "sortiront"],
    [
      "sortirais",
      "sortirais",
      "sortirait",
      "sortirions",
      "sortiriez",
      "sortiraient",
    ],
    {
      present: "Irregular -ir: sor-/sort- stem alternation",
      perfect: "Uses être: suis sorti(e)",
    },
  ),
  frVerb(
    "tenir",
    "to hold",
    "irregular",
    49,
    ["common"],
    ["tiens", "tiens", "tient", "tenons", "tenez", "tiennent"],
    ["tenais", "tenais", "tenait", "tenions", "teniez", "tenaient"],
    ["ai tenu", "as tenu", "a tenu", "avons tenu", "avez tenu", "ont tenu"],
    ["tiendrai", "tiendras", "tiendra", "tiendrons", "tiendrez", "tiendront"],
    [
      "tiendrais",
      "tiendrais",
      "tiendrait",
      "tiendrions",
      "tiendriez",
      "tiendraient",
    ],
    {
      present: "Irregular: tien-/ten-/tienn- stem alternation (like venir)",
      future: "Irregular future stem: tiendr-",
    },
  ),
  frVerb(
    "courir",
    "to run",
    "irregular",
    50,
    ["common"],
    ["cours", "cours", "court", "courons", "courez", "courent"],
    ["courais", "courais", "courait", "courions", "couriez", "couraient"],
    [
      "ai couru",
      "as couru",
      "a couru",
      "avons couru",
      "avez couru",
      "ont couru",
    ],
    ["courrai", "courras", "courra", "courrons", "courrez", "courront"],
    ["courrais", "courrais", "courrait", "courrions", "courriez", "courraient"],
    { future: "Irregular future stem: courr- (double r)" },
  ),
];

// ========================================================================
// Combined seed data
// ========================================================================
export const ALL_SEED_DATA: VerbSeedData[] = [...GERMAN_VERBS, ...FRENCH_VERBS];
